/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-container-high': '#e9e8e4',
        'on-tertiary-fixed-variant': '#544520',
        'on-primary-container': '#858383',
        'on-surface-variant': '#444748',
        'on-tertiary-fixed': '#251a00',
        'surface-dim': '#dbdad6',
        'surface-container-low': '#f4f4f0',
        'on-primary': '#ffffff',
        'outline-variant': '#c4c7c7',
        'surface-container-highest': '#e3e2df',
        'secondary-container': '#fed65b',
        'on-error': '#ffffff',
        'primary-fixed': '#e5e2e1',
        tertiary: '#6d5c35',
        'secondary-fixed-dim': '#e9c349',
        'surface-bright': '#faf9f5',
        background: '#faf9f5',
        error: '#ba1a1a',
        'primary-container': '#1c1b1b',
        'on-secondary': '#ffffff',
        'on-primary-fixed-variant': '#474746',
        'secondary-fixed': '#ffe088',
        'tertiary-fixed-dim': '#dbc494',
        'on-tertiary': '#ffffff',
        'primary-fixed-dim': '#c8c6c5',
        'on-secondary-fixed-variant': '#574500',
        'inverse-primary': '#c8c6c5',
        'surface-container-lowest': '#ffffff',
        'on-surface': '#1b1c1a',
        'error-container': '#ffdad6',
        'on-secondary-fixed': '#241a00',
        primary: '#000000',
        'on-primary-fixed': '#1c1b1b',
        'surface-variant': '#e3e2df',
        'on-tertiary-container': '#4c3d19',
        'on-background': '#1b1c1a',
        secondary: '#735c00',
        'tertiary-container': '#bea97a',
        'surface-tint': '#5f5e5e',
        'inverse-surface': '#2f312e',
        outline: '#747878',
        'tertiary-fixed': '#f8e0ae',
        'on-secondary-container': '#745c00',
        surface: '#faf9f5',
        'inverse-on-surface': '#f2f1ed',
        'surface-container': '#efeeea',
        'on-error-container': '#93000a',
      },
      fontFamily: {
        headline: ['Newsreader', 'serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
    },
  },
  plugins: [],
};
